# Generated by Django 3.2.6 on 2021-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='album',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
