# Generated by Django 3.2.6 on 2021-08-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0002_auto_20210822_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
