# Generated by Django 3.2.6 on 2021-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0003_auto_20210823_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(max_length=20)),
                ('youtube', models.CharField(max_length=20)),
                ('CompteInsta', models.URLField()),
                ('CompteYoutube', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=450),
        ),
    ]
