# Generated by Django 3.2.6 on 2021-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0004_auto_20210823_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=100)),
                ('prix', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='prix',
        ),
    ]
