# Generated by Django 3.2.6 on 2021-08-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0005_auto_20210823_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='titre',
            field=models.CharField(default='par défaut', max_length=15),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
