# Generated by Django 3.2.6 on 2021-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0006_auto_20210823_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
