# Generated by Django 3.2.6 on 2021-09-12 11:52

from django.db import migrations, models
import lfapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0008_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(storage=lfapp.storage.PublicStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, storage=lfapp.storage.PublicStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo',
            field=models.ImageField(blank=True, storage=lfapp.storage.PublicStorage(), upload_to=''),
        ),
    ]
